### ISSUE TITLE
Cannot get it working when .har is attached after test method

### ISSUE THREAD

**Issue by tlytvyn** [kolsys/allure-harviewer#3]
I am attaching HAR file in a test listener and it appears in TearDown TestNG section. In this case "Inspect Requests" tab is not displayed. When I am attaching HAR during a test method itself everything works, but when .har is attached in AfterMethod it doesn't work.
I wonder maybe it is possible to change somehow `data.testStage.attachments` to after methods attachments in index.js ?

**Comment by tlytvyn** [comment]
Actually fixed that:
`var afterStagesArray = data.afterStages
      for (var i in afterStagesArray) {
          for (var j in afterStagesArray[i].attachments) {
              var attach = afterStagesArray[i].attachments[j];
              if (attach.name.match(/\.har$/)) {
                  links.push({url: 'data/attachments/' + attach.source, name: attach.name});
              }
          }
      }`

**Comment by devmaster-st** [comment]
> Actually fixed that:
> `var afterStagesArray = data.afterStages for (var i in afterStagesArray) { for (var j in afterStagesArray[i].attachments) { var attach = afterStagesArray[i].attachments[j]; if (attach.name.match(/\.har$/)) { links.push({url: 'data/attachments/' + attach.source, name: attach.name}); } } }`

Hello. Could you give your edited index.js?
