### ISSUE TITLE
Support in jest

### ISSUE THREAD

**Issue by hananmalka** [kolsys/allure-harviewer#4]
Hi,

Thanks for this plugin. 
I enabled this plugin and still can't watch the har file in the viewer.
The file has the extension *.har but still can't watch it. 

Does this plugin supports with adding attachment using jest or just via java @addAttachment?

**Comment by kolsys** [comment]
The plugin just watch *.har files in the data.testStage.attachments property. Do you see your har file in this list?

**Comment by hananmalka** [comment]
What is "data.testStage.attachments property"? 
I'm executing allure generate command to generate the report and I can see the file under attachments directory and it has the extension ".har"
In addition, the plugin is enabled.

I can see it under the test case json file:
` "attachments" : [ {
      "uid" : "2d23337761804015",
      "name" : "Screenshot",
      "source" : "2d23337761804015.png",
      "type" : "image/png",
      "size" : 95233
    }, {
      "uid" : "50f7997f416fe352",
      "name" : "HAR Record",
      "source" : "50f7997f416fe352.har",
      "type" : "text/plain",
      "size" : 15902004
    } ],`

**Comment by kolsys** [comment]
Sorry, I don't have access to the test stand anymore and forget how to debug this. But the data.testStage.attachments you can see under Web inspector while you open the test case in allure.
The json looks ok. Please show full parent node of the attachments property.
